name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/LLM-stock-news-analysis
            git pull
            echo "Fetched latest code from GitHub."
            source .venv/bin/activate
            echo "Activated Python virtual environment."
            pip install -r requirements.txt
            echo "Installed/updated Python packages."
            echo "Deployment to VM successful!" 